[package]
name="relm4-store-reexport"
version= "0.1.0"
edition = "2018"
description = "Place holding all dependencies for relm4-store in single place"

keywords = ["model", "data"]
readme = "README.md"

[dependencies]
log = "0.4.14"
relm4 = "0.2.1"
relm4-macros = "0.2.1"
relm4-components = "0.2.1"
tracker = "^0.1.1"
gtk = { version = "0.3.1", package = "gtk4" }
uuid = { version = "^0.8.2", features = ["serde", "v4"] }
adw = { version = "0.1.0-alpha-5", optional = true, package = "libadwaita" }
